[package]
name = "witgen"
version = "0.1.0"
authors = ["Den <denbite.team>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = { version = "1.0.32", features = ["span-locations"] }